=== rdbwebster/CustomXpathFunctions/Project1/xsd/FileEmployee.xsd
<?xml version="1.0" encoding="windows-1252" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
            xmlns="http://www.example.org"
            targetNamespace="http://www.example.org"
            elementFormDefault="qualified">

   <xs:element name="Employees" type="EmpCollection"/>
   <xs:complexType name="EmpCollection">
      <xs:sequence>
         <xs:element name="Emp" type="Emp" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Emp">
      <xs:sequence>
         <xs:element name="number" type="xs:int"/>
         <xs:element name="firstName" nillable="true">
            <xs:simpleType>
               <xs:restriction base="xs:string">
                  <xs:maxLength value="10"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:element>
          <xs:element name="lastName" nillable="true">
            <xs:simpleType>
               <xs:restriction base="xs:string">
                  <xs:maxLength value="10"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:element>
         <xs:element name="job" nillable="true">
            <xs:simpleType>
               <xs:restriction base="xs:string">
                  <xs:maxLength value="12"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:element>
         <xs:element name="hiredate" type="xs:date" nillable="true"/>
         <xs:element name="dept" type="xs:int" nillable="true"/>
      </xs:sequence>
   </xs:complexType>
</xs:schema>

=== rdbwebster/CustomXpathFunctions/Project1/xsd/Employees.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="./FileEmployee.xsd"
           xmlns="http://www.example.org">
  <Emp>
    <number>2315</number>
    <firstName>Bob</firstName>
    <lastName>Jones</lastName>
    <job>Clerk</job>
    <hiredate>2002-09-24</hiredate>
    <dept>103</dept>
  </Emp>
  <Emp>
    <number>2315</number>   <!-- deliberate duplicate for human intervention -->
    <firstName>Mary</firstName>
    <lastName>Laroche</lastName>
    <job>Purchaser</job>
    <hiredate>1999-09-24</hiredate>
    <dept>207</dept>
  </Emp>
</Employees>
